version: '3.7'

services:
    vinayb-titlebanner-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: vinayb-titlebanner-img
      # container_name: titleBanner-node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "3001:3001"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: vinayb-titleBanner-mongodb
      ports:
        - "27017:27017"